#!/bin/bash

# Unofficial bash strict mode http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -eu
set -o pipefail
IFS=$'\n\t'

cp /app/sshd_config /etc/ssh/sshd_config

ssh-keygen -A

echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDF4/IGL8u2y68gVp7AKb7qG5XMOgfFZFw1HSG1GiOfaGnT1VlLg+rWxngr340kI4ThLJn4XjcdcM5JMUnfwEw51IG3wLksS4oVFATbWh2MFelczh4BxZ5TSLBT4uYDx6WY5OHhc6fA6m7PfkvVdcaQ8RAbJvksL7QfR1xcwu86HLZtcy/QuszY1U6ii2T+fkA5xDc9CUV6qY4BgOBkerCBsOU05DmrbcbEWsSObtqF8N17KxQydpXc00qT9QGoX/29qSm8Ef3piyP03nU6VTco5s5XFk5qz+n5qrBpVDxNunDXGqM2klCyEImxpn3oEaajXDeMt/OMaaumOl8sOmF9" > /etc/ssh/authorized_keys/arq

chown root /home/arq
chmod o-rwx /home/arq
mkdir -p /home/arq/sftp
chown arq /home/arq/sftp

echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIO34KEmj8G9aDfh549JRg7QPo5hgohiHqa/s23Ng6v0B" > /etc/ssh/authorized_keys/adrien

exec ${*:1}
